### PR TITLE
add: Japanese translation

### PR DESCRIPTION
**Pull request by incisakura**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ x ] Acknowledge that you're contributing your code under Apache v2.0 license

- [ - ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

Sorry, I just done this translation by VS Code.

### CODE REVIEW

**Comment by SakuraSa233** [comment]
Please **DO NOT** merge this pull request now.
I need fix some mistake.

**Comment by SakuraSa233** [comment]
Now, it would be OK to merge.

**Comment by barbeau** [comment]
@SakuraSa233 Thanks for contributing this!  Would you mind moving the changes to the Chinese translation to a separate pull request?  I'd like to have some of the past contributors of the Chinese translation review as well.  Thanks!

**Comment by SakuraSa233** [comment]
@barbeau Sorry, I don't know how to do that.....

Cloud you tell me?(stupid

**Comment by barbeau** [comment]
Thanks @SakuraSa233!

**Comment by barbeau** [comment]
@SakuraSa233 This translation is now available in beta v3.2.9.  Please take a look!

**Pull request merged**
