### PR TITLE
Add SouthPAN to SatelliteUtil,kt

### PR DESCRIPTION
**Pull request by davecollett**
SouthPAN has PRN122 assigned

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x ] Acknowledge that you're contributing your code under Apache v2.0 license

- [x ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

### CODE REVIEW

**Comment by davecollett** [comment]
This is related to https://github.com/barbeau/gpstest/issues/598
SouthPAN is expected to begin early services on PRN122 later this year.

**Comment by davecollett** [comment]
Sorry, was a bit premature with this pull request, will look to replicate this PR:
https://github.com/barbeau/gpstest/commit/5373ddbbfee5d8742f7bad0086408c26aa23a644

**Comment by barbeau** [comment]
@davecollett Thanks for working on this! Yes, that commit is a good model. You'll need to add the new type to the enumeration. For this one need to add a flag image as well and include it in Status and Sky user interface code. Here's Status:
https://github.com/barbeau/gpstest/blob/b4f18fc3454009d82780a5fe3fa8fbfbd6f475fa/GPSTest/src/main/java/com/android/gpstest/ui/status/StatusScreen.kt#L240

And Sky:
https://github.com/barbeau/gpstest/blob/b4f18fc3454009d82780a5fe3fa8fbfbd6f475fa/GPSTest/src/main/res/layout/gps_sky_legend_card.xml#L35

**Comment by davecollett** [comment]
Happy to try and help, i really appreciate the app.
The flag is a bit of a challenge to represent the two countries, but will
come up with something.

**Pull request closed without merging**
