### PR TITLE
feat: Upload device capabilities to public GPSTest Device Database

### PR DESCRIPTION
**Pull request by barbeau**
One of the top questions I get from users is "what GNSS capabilities does X have?" for devices. I've tried to maintain a list in the FAQ for this:
https://github.com/barbeau/gpstest/blob/master/FAQ.md#what-devices-support-the-various-functionality-shown-in-gpstest

...but it's too labor intensive to keep up with when being emailed by users.

This PR adds the ability for users to upload device capabilities directly to a public [GPSTest Device Database](https://docs.google.com/spreadsheets/d/1jXtRCoEnnFNWj6_oFlVWflsf-b0jkfZpyhN-BXsv7uo/edit?usp=sharing) (aka Google Sheet). Hopefully this results in a scalable solution where users can easily contribute device capabilities.

TODO app:
- [x] Convert Share dialog to fragment with tabs (viewpager2)
- [x] Implement basic upload infrastructure
- [x] When logging not enabled, fix visibility of "File name" TextView (it should be GONE)
- [x] Add progress bar during upload
- [x] Add hyperlink to Sheet in upload tab text
- [x] Move registration of various listeners to startup instead of being enabled for logging
- [x] Filter out emulator submissions
- [x] Complete remaining device properties
    - [x] SUPPORTED_GNSS
    - [x] GNSS_CFS
    - [x] SUPPORTED_SBAS
    - [x] SBAS_CFS
    - [ ] hardware clock - see https://source.android.com/reference/hal/struct_gnss_clock for fields that must be populated when receiver has estimated time (EDIT - not sure what this should be to generalize across device model - going to wait for more info)
    - [ ] hardware clock discontinuity - https://developer.android.com/reference/android/location/GnssClock#getHardwareClockDiscontinuityCount() (EDIT - not sure what this should be to generalize across device model - going to wait for more info)
    - [ ] GNSS fix special type from NMEA? - Differential, RTK fixed int, RTK float int, https://www.trimble.com/OEM_ReceiverHelp/V4.44/en/NMEA-0183messages_GGA.html
- [x] Sort sets before uploading
- [x] Off switch is broken? It seems to keep running. **EDIT** - Apparently when we have the measurements listener always listening, it causes the GnssStatus to continue reporting even when location updates via LocationListener are unregistered. So the fix is to explicitly stop listening from measurements when flipping the switch, and then re-enable them when flipping the UI switch back on. Not sure if this is intended Android behavior or a Samsung bug - tested on Galaxy S8+ / Android 9.
- [x] Fix Share dialog height when file logging isn't enabled
- [x] Optimize tab loading to one tab only? If this changes it causes the above Share dialog height issue. So load all the fragments at once to make sure height is measured correctly.
- [x] Check for existing fragments from FM before creating new ones?
- [x] Accuracy card size needs to be updated
- [x] Check for duplicates? Hash values (without app version) to see if they've changed
- [x] What if Status fragment isn't active? How to handle variables like dual-frequency from viewmodel
- [x] Can we get rid of multidex? **EDIT** - Doesn't look like it :( 
- [x] Put share fragments in vertically scrolling container for horizontal orientation - **EDIT** ScrollView doesn't seem to work within ViewPager2 in DialogFragment? I get no scrolling effect and text bleeds into tabs. Leaving as-is for now, as it's still functional as-is.
- [x] Travis is failing - same on master branch - issue opened here - https://github.com/barbeau/gpstest/issues/451

Server-side TODO:
- [x] Derive market device name from MODEL? See https://github.com/jaredrummler/AndroidDeviceNames. Follow links there to this Google list - https://storage.googleapis.com/play_public/supported_devices.csv.
- [x] Filter out emulator submissions
- [x] Capitalize first letter of manufacturer
- [ ] Check for duplicates?

### CODE REVIEW

**Comment by barbeau** [comment]
Tests pass on my machine with `./gradlew testcheck connectedCheck` so I'm merging. Will look into test failures on CI and in Android Studio in https://github.com/barbeau/gpstest/issues/451.

**Comment by barbeau** [comment]
Oh, I'm wrong - I was running the master branch by mistake. Tests fail locally just like Travis:

~~~
> Task :GPSTest:testGoogleDebugUnitTest FAILED

com.android.gpstest.util.UIUtilsTest > testSnrToTextViewLeftMargin FAILED
    java.lang.NoClassDefFoundError at UIUtilsTest.java:85
        Caused by: java.lang.ClassNotFoundException at UIUtilsTest.java:85

com.android.gpstest.util.UIUtilsTest > testCn0ToTextViewLeftMargin FAILED
    java.lang.NoClassDefFoundError at UIUtilsTest.java:63
        Caused by: java.lang.ClassNotFoundException at UIUtilsTest.java:636,javaHome=C:\Program Files\Java\jdk1.8.0_112,daemonRegistryDir=C:\Users\sjbar\.grad
le\daemon,pid=25444,idleTimeout=10800000,priority=NORMAL,daemonOpts=-XX:MaxPermSize=2048m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx3g,-Dfile.encoding=UTF-8,-Duser.
com.android.gpstest.util.UIUtilsTest > testCn0ToIndicatorLeftMarginPx FAILED
    java.lang.NoClassDefFoundError at UIUtilsTest.java:19.daemon.client.DaemonClientConnection] thread 1: dispatching class org.gradle.launcher.daemon.protoco
        Caused by: java.lang.ClassNotFoundException at UIUtilsTest.java:19
2020-12-01T13:42:00.263-0500 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: connection stop
com.android.gpstest.util.UIUtilsTest > testSnrToIndicatorLeftMarginPx FAILED
    java.lang.NoClassDefFoundError at UIUtilsTest.java:41
        Caused by: java.lang.ClassNotFoundException at UIUtilsTest.java:41
> IDLE
com.android.gpstest.util.UIUtilsTest > testToMilesPerHour FAILED
    java.lang.NoClassDefFoundError at UIUtilsTest.java:132
        Caused by: java.lang.ClassNotFoundException at UIUtilsTest.java:132
> :GPSTest:compileGoogleDebugKotlin
com.android.gpstest.util.UIUtilsTest > testToKilometersPerHour FAILED
    java.lang.NoClassDefFoundError at UIUtilsTest.java:118
        Caused by: java.lang.ClassNotFoundException at UIUtilsTest.java:118

com.android.gpstest.util.UIUtilsTest > testToFeet FAILED
    java.lang.NoClassDefFoundError at UIUtilsTest.java:104
        Caused by: java.lang.ClassNotFoundException at UIUtilsTest.java:104

14 tests completed, 7 failed
~~~

**Comment by barbeau** [comment]
So after updating Gradle plugin, wrapper and Kotlin dependency to JDK 8, as well as updating the test dependencies, the unit tests now pass on API >=21 but are failing with a different error on APIs 18 and 19:
https://travis-ci.org/github/barbeau/gpstest/builds/747082174

Here's the error on APIs 18 and 19 - it can't find the instrumented tests to execute them:

~~~
> Task :GPSTest:connectedGoogleDebugAndroidTest
Starting 0 tests on test(AVD) - 4.4.2
com.android.build.gradle.internal.testing.ConnectedDevice > No tests found.[test(AVD) - 4.4.2] FAILED 
No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @Test annotations).
> Task :GPSTest:connectedGoogleDebugAndroidTest FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':GPSTest:connectedGoogleDebugAndroidTest'.
> There were failing tests. See the report at: file:///home/travis/build/barbeau/gpstest/GPSTest/build/reports/androidTests/connected/flavors/googleDebugAndroidTest/index.html
~~~

**Comment by barbeau** [comment]
Travis has been taking forever lately, so I'm merging. Tests pass locally except for APIs 18 and 19 (they aren't recognized there), which I have an issue open for here - https://github.com/barbeau/gpstest/issues/453. App seems to execute fine on API 19 emulator.

**Comment by KovalevArtem** [comment]
Which link should I go to to view the database? 😅

**Comment by barbeau** [comment]
Oh yes, would probably help if I added that here 😄.

Shortened link to the Google Sheet is:
https://bit.ly/gpstest-device-database

More info in this Google group post on the v3.9.0 beta release that includes this feature:
https://groups.google.com/g/gpstest_android/c/cRs-smxwAJ8/m/V5-7J1ryAQAJ

**Comment by KovalevArtem** [comment]
Check for duplicates
image
Removing duplicates doesn't seem like a good idea to me. Because the data for ONE specific phone model (for some reason) can vary significantly ...
At this point, I think it's better to let the user filter and analyze ALL of the results that are in the database ...

**Comment by barbeau** [comment]
@KovalevArtem Agreed, removing "duplicates" needs to be done delicately. I'm closely monitoring any removed records, and it's not just based on "Model" - there is [a lot of logic](https://github.com/barbeau/gpstest/blob/master/scripts/database.js#L241) in the check, and records with different "GNSS hardware model names" will always be retained.

The records you reference are a good example. It shows that the Mi 10 lite 5G didn't support dual-frequency on `qcom;MPSS.HI.1.0.c8.11-00070-SAIPAN_GEN_PACK-1;` (which corresponds to Android software version `V11.0.4.0.QJIEUSF` - see column AD), but it appears when it was updated to `qcom;MPSS.HI.1.0.c8.11-00057-SAIPAN_GEN_PACK-1.330232.1.331177.1;` (which correponds to Android software version `V12.0.3.0.QJIEUXM` - a major release) then dual-frequency was supported.

I've been writing a Medium article explaining all this in more detail that's almost done, and I'll post that here when I'm done.

**Comment by barbeau** [comment]
Sorry, I wasn't clear above how the duplicates are removed - all submissions from devices end up in the Google Sheet (unless the same device tries to submit the exact same information), and then I have the server-side script I can run to log and remove duplicates which I linked to above. So I can run it manually for now and view the logs, and restore any records that should still exist there.

**Comment by barbeau** [comment]
FYI, here is the article describing the general GPSTest Database feature, with motivation and how-to:
https://barbeau.medium.com/crowdsourcing-gnss-capabilities-of-android-devices-d4228645cf25

...and here is the article describing the implementation:
https://barbeau.medium.com/implementing-the-gpstest-database-a-serverless-architecture-c61a2084965

**Pull request merged**
