### PR TITLE
Add French Translation

### PR DESCRIPTION
**Pull request by bugeaud**
Hello Sean,

As requested on https://github.com/barbeau/gpstest/issues/246 please find attached the french translation.

- [x] Acknowledge that you're contributing your code under Apache v2.0 license

- [] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
       JB> Not done since I only used text replace in the XML file forking from the existing English variants.

Best Regards,
JB

### CODE REVIEW

**Comment by barbeau** [comment]
@bugeaud Thanks for submitting this!  Looks like the Travis build is currently failing with these types of errors:

~~~
/home/travis/build/barbeau/gpstest/GPSTest/build/intermediates/incremental/mergeGoogleDebugResources/merged.dir/values-fr/values-fr.xml:65: error: unescaped apostrophe in string
  "Certains équipements ne rafraichissent les données d'assistances que tous les 24 heures. Si votre équipement ne permet pas l'injection manuelle, la localisation peut ne plus fonctionner d'ici au prochain rafraichissement. Confirmez-vous l'injection\u202F?".
~~~

On Android you need to add a `\` before all apostrophes.  So `l'injection` should be `l\'injection`.

Could you please add this for all the apostrophes in both files, and also sign the CLA?  Thanks!

**Comment by bugeaud** [comment]
I've fixed the escaping.

Sorry to raise the point, but I tend to read before signing things and I do have some issues with the CLA. This is way too broad IMHO : like killing a fly with a thermonuclear weapon. Sure it kills the fly, but there are tons of unwanted side effects ... Why can't we just contribute translations under some usual licence say Creative Commons ? Something like CC-BY-SA should be fine for both party as a good start => you can do whatever you want with the translated files (no limitation outsite what the licence state). This is just a translation nothing like source code, secret sauce or whatever... CC-BY-SA should by just enought and wile have no impact with my past, actual or future employers/customers because it is of limited scope : the work itself.

**Comment by barbeau** [comment]
@bugeaud Given my limited bandwidth to work on the app (it's a side project for me), at this point I'd prefer to lean towards keeping things simple to maintain, which means requiring the CLA for all contributions.  It's ok if you disagree and don't want to contribute given the current CLA.  Just let me know.

**Comment by barbeau** [comment]
@bugeaud any further thoughts on signing the CLA to contribute your French translation?

I'm going to close this PR for record-keeping because it's been open a while, but if you're still interested in contributing we can re-open.

Also, going forward I'll be using Transifex to manage translations (although we could still merge this PR):
https://www.transifex.com/sean-barbeau/gpstest-android/dashboard/

**Comment by bugeaud** [comment]
Hello Sean, the current CLA has multiple legal issues for any signee. Mainly it holds little limit on its impacts : time, perimeter, third party... As not limited, it could be seen as unbalanced and could be discarded by legal juridiction. I do understand you are tyring to protect your back. But I don't think that outside north-america, this legal text will have much coverage in that perspective.

Clearly, I did not make this translation to jump into a legal bandwagon but simply to contribute to this nice tool you made.

Feel free to contact me again if you decide to pick any known licence that we can simply get a clear legal impact analysis for outside north-america.

**Pull request closed without merging**
