### PR TITLE
Patch 3

### PR DESCRIPTION
**Pull request by LLZN**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Acknowledge that you're contributing your code under Apache v2.0 license

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

### CODE REVIEW

**Comment by barbeau** [comment]
@LLZN Thanks for working on this!  Would you mind adding your translation for both strings.xml and arrays.xml via Transifex?

https://www.transifex.com/sean-barbeau/gpstest-android/dashboard/

I'll be using this platform to manage translations going forward.  Thanks!

**Comment by LLZN** [comment]
Hello, I finished the translation today (www.transifex.com), maybe there
will be some.  I have a request to send a beta version of the app with a
Czech translation to check ... Or download link.  Thank you

Dne st 17. 4. 2019 18:58 uživatel Sean Barbeau <notifications@github.com>
napsal:

**Comment by barbeau** [comment]
@LLZN Thanks! Could you please uninstall your current GPSTest version and try this build which should include your translation:
https://www.dropbox.com/s/6e95qg800jjx94r/GPSTest-google-debug.apk?dl=0

**Comment by LLZN** [comment]
ok

Dne po 22. 4. 2019 18:44 uživatel Sean Barbeau <notifications@github.com>
napsal:

**Pull request closed without merging**
