### PR TITLE
Fix #81 - Update README with F-Droid button

### LINKED ISSUE #81: F-droid availability
Are you able to make gpstest available on [f-droid](http;//f-droid.org) for those of us who do not use Google apps?

### PR DESCRIPTION
**Pull request by Poussinou**
- [x] Acknowledge that you're contributing your code under Apache v2.0 license

- [x] If you have multiple commits please combine them into one commit by squashing them.

This small PR adds two buttons to get your app on F-Droid and Google Play 👍 

close #81

### CODE REVIEW

**Comment by barbeau** [comment]
Thanks @Poussinou!  Could you please sign the [Contributor License Agreement](https://cla-assistant.io/barbeau/gpstest?pullRequest=165) so I can merge?

**Comment by Poussinou** [comment]
Sorry but they're asking for my phone number and I don't wanna give it for such a little PR.

You're allowed to take the small lines I wrote, and put it in the README yourself ;)

**Comment by barbeau** [comment]
@Poussinou Sure, no problem.  Thanks for the PR!  I added the badges in https://github.com/barbeau/gpstest/commit/725a45ee53858cd3d1b3d294ae32de22b244b6ae.

**Comment by Poussinou** [comment]
Thanks for your understanding 👍

**Pull request closed without merging**
