### PR TITLE
Replace dead link in README.md

### PR DESCRIPTION
**Pull request by slanterns**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Acknowledge that you're contributing your code under Apache v2.0 license

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

### CODE REVIEW

**Comment by barbeau** [comment]
Thanks for the PR! Could you please use this link instead https://www.euspa.europa.eu/newsroom-events/news-archive/test-your-android-devices-satellite-navigation-performance ?

**Comment by slanterns** [comment]
Done.

**Comment by slanterns** [comment]
图片
Their moved page still uses a dead link to the original source, though  🤔.

**Comment by barbeau** [comment]
Thanks!

**Pull request merged**
