### PR TITLE
Android 6.0 permission check & SkyView legend

### PR DESCRIPTION
**Pull request by cachewind**
Update:
Android 6.0 permission check.
SkyView legend.

### CODE REVIEW

**Comment by cachewind** [comment]
I think it may caused by you don't have 23 API. The easiest way - download API 23.
Beginning in Android 6.0 (API level 23), users grant permissions to apps while the app is running, not when they install the app. To give users this flexibility and to make sure your app behaves as expected when an Android Marshmallow user disables a specific permission, it’s important that you update your app to target API 23.

**Comment by barbeau** [comment]
@cachewind Sorry for the delay reviewing this, and thanks for the contribution!  I'm going to close and re-open the PR so you can sign the ICLA via the new ICLA bot.  After you do that, I'll look at merging these contributions manually, as I've introduce some conflicts with recent changes.

**Comment by barbeau** [comment]
@cachewind I'm revisiting this issue re: legend - would you be able to sign the CLA so I can merge some of your code?  Thanks!

**Comment by barbeau** [comment]
@cachewind Friendly ping - would you be able to sign the CLA so I can merge some of your code? Thanks!

**Comment by cachewind** [comment]
done

**Comment by barbeau** [comment]
@cachewind Thanks!

**Comment by tolstman88** [comment]
upi

**Comment by barbeau** [comment]
@cachewind Thanks for opening this. After looking at this a bit I'm pursuing a different strategy for the legend based on XML layouts instead of drawing on the canvas. I appreciate your efforts to contribute back to this app!

**Pull request closed without merging**
