### PR TITLE
German translation update

### PR DESCRIPTION
**Pull request by SIRSteiner**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Acknowledge that you're contributing your code under Apache v2.0 license

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

### CODE REVIEW

**Comment by SIRSteiner** [comment]
Don't know why Travis Ci failed?
I did many changes in help section. Please let me check it with a prerelease. Thanks

**Comment by barbeau** [comment]
@SIRSteiner Thanks! Looks like the Travis build fail is unrelated to your PR, I'll take a look.

I'll go ahead and merge this.  Going forward, I want to use Transifex to manage translations, so please create an account there and use this to create translations:
https://www.transifex.com/sean-barbeau/gpstest-android/dashboard/

It should be easier to create translations there too.

**Comment by Giolly90** [comment]
Hi, I would like to contribute with translation into Italian

**Comment by barbeau** [comment]
@SIRSteiner Could you please uninstall your current GPSTest version and try this one with your new translation:
https://www.dropbox.com/s/6e95qg800jjx94r/GPSTest-google-debug.apk?dl=0

@Giolly90 That would be great!  I just added it as a language on Transifex, so you can translate it there:
https://www.transifex.com/sean-barbeau/gpstest-android/language/it/

Please check out this page if you have any questions:
https://github.com/barbeau/gpstest/blob/master/TRANSLATIONS.md

**Comment by SIRSteiner** [comment]
Now I have an account at transifex. Please upload the latest translation file ;-)

**Comment by barbeau** [comment]
@SIRSteiner I think newest file should be there now?  When I merged this PR it should have updated automatically...

**Comment by SIRSteiner** [comment]
@barbeau I installed the test version and found many layout problems in german help text. Therefore I installed Android Studio, did another translation update with a new layout (I used big- and li-tags) and compiled the apk myself ;-) Here it looks nice.
At transifex there is no update visible. This is not a problem for me, I always can do commit at github and create a pull request.

**Pull request merged**
