### PR TITLE
Update german translation

### PR DESCRIPTION
**Pull request by SIRSteiner**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Acknowledge that you're contributing your code under Apache v2.0 license

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by SIRSteiner** [comment]
It seems that all strings are right but the help screen cashes the app. So I cannot check that finally. Because there is no possibility to send a feedback here is the catlog:

`08-08 20:21:34.793 I/ActivityManager(  827): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.android.gpstest/.GpsTestActivity bnds=[657,1442][891,1704] (has extras)} from uid 10030 on display 0
08-08 20:21:34.795 I/am_create_task(  827): [0,93158]
08-08 20:21:34.795 I/am_create_activity(  827): [0,20199219,93158,com.android.gpstest/.GpsTestActivity,android.intent.action.MAIN,NULL,NULL,270532608]
08-08 20:21:34.796 I/wm_task_created(  827): [93158,1]
08-08 20:21:34.797 I/wm_task_moved(  827): [93158,1,21]
08-08 20:21:34.797 I/am_focused_stack(  827): [0,1,0,startedActivity setFocusedActivity]
08-08 20:21:34.798 I/wm_task_moved(  827): [93158,1,21]
08-08 20:21:34.800 I/am_focused_activity(  827): [0,com.android.gpstest/.GpsTestActivity,startedActivity]
08-08 20:21:34.801 I/am_pause_activity(  827): [0,43439872,com.cyanogenmod.trebuchet/com.android.launcher3.Launcher]
08-08 20:21:34.804 I/sysui_action(  827): [323,com.android.gpstest/.GpsTestActivity]
08-08 20:21:34.804 I/sysui_action(  827): [324,false]
08-08 20:21:34.804 I/sysui_action(  827): [325,337055]
08-08 20:21:34.809 W/BroadcastQueue(  827): Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$GmsExternalReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.cyanogenmod.trebuchet (uid 10030)
08-08 20:21:34.811 I/am_on_paused_called(11376): [0,com.android.launcher3.Launcher,handlePauseActivity]
08-08 20:21:34.823 I/am_proc_start(  827): [0,6280,10374,com.android.gpstest,activity,com.android.gpstest/.GpsTestActivity]
08-08 20:21:34.823 I/ActivityManager(  827): Start proc 6280:com.android.gpstest/u0a374 for activity com.android.gpstest/.GpsTestActivity
08-08 20:21:34.826 I/sysui_count(  827): [window_time_0,8]
08-08 20:21:34.849 I/am_proc_bound(  827): [0,6280,com.android.gpstest]
08-08 20:21:34.855 I/am_restart_activity(  827): [0,20199219,93158,com.android.gpstest/.GpsTestActivity]
08-08 20:21:34.862 I/notification_enqueue(  827): [1000,827,android,17039403,NULL,0,Notification(pri=-1 contentView=null vibrate=null sound=null defaults=0x0 flags=0x2 color=0x00000000 vis=PRIVATE),0]
08-08 20:21:34.887 W/System  ( 6280): ClassLoader referenced unknown path: /data/app/com.android.gpstest-2/lib/arm
08-08 20:21:34.897 I/sysui_action(  827): [321,106]
08-08 20:21:34.898 I/sysui_action(  827): [320,1]
08-08 20:21:34.899 I/sysui_action(  827): [319,108]
08-08 20:21:34.922 I/sf_frame_dur(  283): [com.cyanogenmod.trebuchet/com.android.launcher3.Launcher,1,2,0,0,3,2,0]
08-08 20:21:34.939 W/art     ( 6280): Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
08-08 20:21:35.018 D/NavDrawerFragment( 6280): Using position from preferences = 0
08-08 20:21:35.020 D/GpsTestActivity( 6280): Creating new GpsStatusFragment
08-08 20:21:35.099 I/GnssLocationProvider(  827): WakeLock acquired by sendMessage(3, 0, com.android.server.location.GnssLocationProvider$GpsRequest@2c83dd9)
08-08 20:21:35.100 E/LocSvc_eng(  827): I/===> int loc_eng_set_position_mode(loc_eng_data_s_type &, LocPosMode &) line 2136 
08-08 20:21:35.100 E/LocSvc_eng(  827): I/===> int loc_eng_start(loc_eng_data_s_type &) line 2017 
08-08 20:21:35.100 E/LocSvc_api_v02(  827): I/---> locClientSendReq line 2055 QMI_LOC_REG_EVENTS_REQ_V02
08-08 20:21:35.101 I/GnssLocationProvider(  827): WakeLock released by handleMessage(3, 0, com.android.server.location.GnssLocationProvider$GpsRequest@2c83dd9)
08-08 20:21:35.107 E/LocSvc_api_v02(  827): I/---> locClientSendReq line 2055 QMI_LOC_SET_OPERATION_MODE_REQ_V02
08-08 20:21:35.112 E/LocSvc_ApiV02(  827): I/<--- void globalRespCb(locClientHandleType, uint32_t, const locClientRespIndUnionType, uint32_t, void *) line 133 QMI_LOC_SET_OPERATION_MODE_REQ_V02
08-08 20:21:35.112 E/LocSvc_api_v02(  827): I/---> locClientSendReq line 2055 QMI_LOC_START_REQ_V02
08-08 20:21:35.175 D/bsthal  (  827): batch, handle: 1598182235, flags: 0, period_ns: 16000000, timeout: 0, index: 2
08-08 20:21:35.175 I/bsthal  (  827): <BST> cur_ns 16000000set delay of <BOSCH Rotation Vector Sensor> to 16ms
08-08 20:21:35.175 D/bsthal  (  827): activate, handle: 1598182235, enabled: 1
08-08 20:21:35.175 I/bsthal  (  827): <BST> enable sensor <BOSCH Rotation Vector Sensor>
08-08 20:21:35.196 E/LocSvc_ApiV02(  827): I/<--- void globalEventCb(locClientHandleType, uint32_t, const locClientEventIndUnionType, void *) line 107 QMI_LOC_EVENT_ENGINE_STATE_IND_V02
08-08 20:21:35.196 E/LocSvc_eng(  827): I/<=== status_cb line 2276 GPS_STATUS_ENGINE_ON
08-08 20:21:35.196 E/LocSvc_eng(  827): I/<=== status_cb line 2276 GPS_STATUS_SESSION_BEGIN
08-08 20:21:35.216 I/am_on_resume_called( 6280): [0,com.android.gpstest.GpsTestActivity,LAUNCH_ACTIVITY]
08-08 20:21:35.291 I/Adreno  ( 6280): QUALCOMM build                   : 73137ba, I09d312ff84
08-08 20:21:35.291 I/Adreno  ( 6280): Build Date                       : 09/25/17
08-08 20:21:35.291 I/Adreno  ( 6280): OpenGL ES Shader Compiler Version: XE031.09.00.03
08-08 20:21:35.291 I/Adreno  ( 6280): Local Branch                     : 
08-08 20:21:35.291 I/Adreno  ( 6280): Remote Branch                    : quic/LA.BR.1.2.9_rb1.26
08-08 20:21:35.291 I/Adreno  ( 6280): Remote Branch                    : NONE
08-08 20:21:35.291 I/Adreno  ( 6280): Reconstruct Branch               : NOTHING
08-08 20:21:35.300 I/OpenGLRenderer( 6280): Initialized EGL, version 1.4
08-08 20:21:35.300 D/OpenGLRenderer( 6280): Swap behavior 1
08-08 20:21:35.385 I/ActivityManager(  827): Displayed com.android.gpstest/.GpsTestActivity: +573ms
08-08 20:21:35.385 I/sysui_action(  827): [322,594]
08-08 20:21:35.385 I/am_activity_launch_time(  827): [0,20199219,com.android.gpstest/.GpsTestActivity,573,573]
08-08 20:21:35.409 I/am_stop_activity(  827): [0,43439872,com.cyanogenmod.trebuchet/com.android.launcher3.Launcher]
08-08 20:21:35.435 I/am_on_stop_called(11376): [0,com.android.launcher3.Launcher,handleStopActivity]
08-08 20:21:35.498 D/wpa_supplicant( 1347): wlan0: Control interface command 'SIGNAL_POLL'
08-08 20:21:35.511 D/wpa_supplicant( 1347): CTRL-DEBUG: global_ctrl_sock-sendto: sock=8 sndbuf=163840 outq=0 send_len=48
08-08 20:21:36.041 E/LocSvc_ApiV02(  827): I/<--- void globalEventCb(locClientHandleType, uint32_t, const locClientEventIndUnionType, void *) line 107 QMI_LOC_EVENT_POSITION_REPORT_IND_V02
08-08 20:21:36.043 W/GpsTestUtil( 6280): Empty DOP values in NMEA: $GPGSA,A,1,,,,,,,,,,,,,,,*1E
08-08 20:21:36.043 D/GpsOutputNmea( 6280): 1533752496041,$GPGSA,A,1,,,,,,,,,,,,,,,*1E
08-08 20:21:36.044 W/GpsTestUtil( 6280): Empty DOP values in NMEA: $GNGSA,A,1,,,,,,,,,,,,,,,*00
08-08 20:21:36.044 D/GpsOutputNmea( 6280): 1533752496041,$GNGSA,A,1,,,,,,,,,,,,,,,*00
08-08 20:21:36.045 D/GpsOutputNmea( 6280): 1533752496041,$GPVTG,,T,,M,,N,,K,N*2C
08-08 20:21:36.046 D/GpsOutputNmea( 6280): 1533752496041,$GPRMC,,V,,,,,,,,,,N*53
08-08 20:21:36.046 W/GpsTestUtil( 6280): Couldn't parse geoid altitude from NMEA: $GPGGA,,,,,,0,,,,,,,,*66
08-08 20:21:36.046 D/GpsOutputNmea( 6280): 1533752496041,$GPGGA,,,,,,0,,,,,,,,*66
08-08 20:21:36.679 E/LocSvc_ApiV02(  827): I/<--- void globalEventCb(locClientHandleType, uint32_t, const locClientEventIndUnionType, void *) line 107 QMI_LOC_EVENT_GNSS_SV_INFO_IND_V02
08-08 20:21:36.679 E/LocSvc_eng(  827): E/Calling gnss_sv_status_cb
08-08 20:21:36.680 E/LocSvc_ApiV02(  827): I/<--- void globalEventCb(locClientHandleType, uint32_t, const locClientEventIndUnionType, void *) line 107 QMI_LOC_EVENT_POSITION_REPORT_IND_V02
08-08 20:21:36.681 D/GpsOutputNmea( 6280): 1533752496680,$GPGSV,3,1,12,01,23,156,,03,63,088,,06,38,303,,09,43,223,*7C
08-08 20:21:36.787 I/art     ( 6280): Do partial code cache collection, code=24KB, data=31KB
08-08 20:21:36.788 I/art     ( 6280): After code cache collection, code=23KB, data=29KB
08-08 20:21:36.788 I/art     ( 6280): Increasing code cache capacity to 128KB
08-08 20:21:37.026 D/GpsOutputNmea( 6280): 1533752496680,$GPGSV,3,2,12,11,01,167,,17,23,246,,18,00,000,,19,29,272,*70
08-08 20:21:37.026 D/GpsOutputNmea( 6280): 1533752496680,$GPGSV,3,3,12,22,40,099,,23,76,192,,25,01,001,,31,18,040,*7C
08-08 20:21:37.027 D/GpsOutputNmea( 6280): 1533752496680,$GLGSV,3,1,10,06,52,052,,22,52,254,,09,03,137,,16,28,088,*66
08-08 20:21:37.027 D/GpsOutputNmea( 6280): 1533752496680,$GLGSV,3,2,10,15,17,021,,05,02,073,,23,25,329,,21,18,194,*6F
08-08 20:21:37.027 D/GpsOutputNmea( 6280): 1533752496680,$GLGSV,3,3,10,07,61,289,,08,14,262,*6C
08-08 20:21:37.029 W/GpsTestUtil( 6280): Empty DOP values in NMEA: $GPGSA,A,1,,,,,,,,,,,,,,,*1E
08-08 20:21:37.029 D/GpsOutputNmea( 6280): 1533752496681,$GPGSA,A,1,,,,,,,,,,,,,,,*1E
08-08 20:21:37.030 W/GpsTestUtil( 6280): Empty DOP values in NMEA: $GNGSA,A,1,,,,,,,,,,,,,,,*00
08-08 20:21:37.030 D/GpsOutputNmea( 6280): 1533752496681,$GNGSA,A,1,,,,,,,,,,,,,,,*00
08-08 20:21:37.031 D/GpsOutputNmea( 6280): 1533752496681,$GPVTG,,T,,M,,N,,K,N*2C
08-08 20:21:37.031 D/GpsOutputNmea( 6280): 1533752496681,$GPRMC,,V,,,,,,,,,,N*53
08-08 20:21:37.032 W/GpsTestUtil( 6280): Couldn't parse geoid altitude from NMEA: $GPGGA,,,,,,0,,,,,,,,*66
08-08 20:21:37.032 D/GpsOutputNmea( 6280): 1533752496681,$GPGGA,,,,,,0,,,,,,,,*66
08-08 20:21:37.681 E/LocSvc_ApiV02(  827): I/<--- void globalEventCb(locClientHandleType, uint32_t, const locClientEventIndUnionType, void *) line 107 QMI_LOC_EVENT_GNSS_SV_INFO_IND_V02
08-08 20:21:37.681 E/LocSvc_ApiV02(  827): I/<--- void globalEventCb(locClientHandleType, uint32_t, const locClientEventIndUnionType, void *) line 107 QMI_LOC_EVENT_POSITION_REPORT_IND_V02
08-08 20:21:37.681 E/LocSvc_eng(  827): E/Calling gnss_sv_status_cb
08-08 20:21:37.695 W/ctxmgr  (13061): [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10034):IndoorOutdoorProducer, vrsn=12874000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 13061). Was: 3 for 57, account#-517948760#
08-08 20:21:37.973 I/art     ( 6280): Do partial code cache collection, code=50KB, data=62KB
08-08 20:21:37.974 I/art     ( 6280): After code cache collection, code=50KB, data=62KB
08-08 20:21:37.974 I/art     ( 6280): Increasing code cache capacity to 256KB
08-08 20:21:38.028 D/GpsOutputNmea( 6280): 1533752497681,$GPGSV,3,1,12,03,63,088,21,01,23,156,,06,38,303,,09,43,223,*7F
08-08 20:21:38.028 D/GpsOutputNmea( 6280): 1533752497681,$GPGSV,3,2,12,11,01,167,,17,23,246,,18,00,000,,19,29,272,*70
08-08 20:21:38.028 D/GpsOutputNmea( 6280): 1533752497681,$GPGSV,3,3,12,22,40,099,,23,76,192,,25,01,001,,31,18,040,*7C
08-08 20:21:38.029 D/GpsOutputNmea( 6280): 1533752497681,$GLGSV,3,1,10,06,52,052,,22,52,254,,09,03,137,,16,28,088,*66
08-08 20:21:38.029 D/GpsOutputNmea( 6280): 1533752497682,$GLGSV,3,2,10,15,17,021,,05,02,073,,23,25,329,,21,18,194,*6F
08-08 20:21:38.029 D/GpsOutputNmea( 6280): 1533752497682,$GLGSV,3,3,10,07,61,289,,08,14,262,*6C
08-08 20:21:38.029 W/GpsTestUtil( 6280): Empty DOP values in NMEA: $GPGSA,A,1,,,,,,,,,,,,,,,*1E
08-08 20:21:38.030 D/GpsOutputNmea( 6280): 1533752497682,$GPGSA,A,1,,,,,,,,,,,,,,,*1E
08-08 20:21:38.030 W/GpsTestUtil( 6280): Empty DOP values in NMEA: $GNGSA,A,1,,,,,,,,,,,,,,,*00
08-08 20:21:38.030 D/GpsOutputNmea( 6280): 1533752497682,$GNGSA,A,1,,,,,,,,,,,,,,,*00
08-08 20:21:38.030 D/GpsOutputNmea( 6280): 1533752497682,$GPVTG,,T,,M,,N,,K,N*2C
08-08 20:21:38.030 D/GpsOutputNmea( 6280): 1533752497682,$GPRMC,,V,,,,,,,,,,N*53
08-08 20:21:38.031 W/GpsTestUtil( 6280): Couldn't parse geoid altitude from NMEA: $GPGGA,,,,,,0,,,,,,,,*66
08-08 20:21:38.031 D/GpsOutputNmea( 6280): 1533752497682,$GPGGA,,,,,,0,,,,,,,,*66
08-08 20:21:38.516 D/wpa_supplicant( 1347): wlan0: Control interface command 'SIGNAL_POLL'
08-08 20:21:38.530 D/wpa_supplicant( 1347): CTRL-DEBUG: global_ctrl_sock-sendto: sock=8 sndbuf=163840 outq=0 send_len=48
08-08 20:21:38.583 E/LocSvc_ApiV02(  827): I/<--- void globalEventCb(locClientHandleType, uint32_t, const locClientEventIndUnionType, void *) line 107 QMI_LOC_EVENT_GNSS_SV_INFO_IND_V02
08-08 20:21:38.583 E/LocSvc_eng(  827): E/Calling gnss_sv_status_cb
08-08 20:21:38.583 E/LocSvc_ApiV02(  827): I/<--- void globalEventCb(locClientHandleType, uint32_t, const locClientEventIndUnionType, void *) line 107 QMI_LOC_EVENT_POSITION_REPORT_IND_V02
08-08 20:21:38.621 D/GpsOutputNmea( 6280): 1533752498584,$GPGSV,3,1,12,03,63,088,25,22,40,099,21,01,23,156,,06,38,303,*71
08-08 20:21:38.621 D/GpsOutputNmea( 6280): 1533752498584,$GPGSV,3,2,12,09,43,223,,11,01,167,,17,23,246,,18,00,000,*79
08-08 20:21:38.621 D/GpsOutputNmea( 6280): 1533752498584,$GPGSV,3,3,12,19,29,272,,23,76,192,,25,01,001,,31,18,040,*7C
08-08 20:21:38.622 D/GpsOutputNmea( 6280): 1533752498584,$GLGSV,3,1,10,06,52,052,,22,52,254,,09,03,137,,16,28,088,*66
08-08 20:21:38.622 D/GpsOutputNmea( 6280): 1533752498584,$GLGSV,3,2,10,15,17,021,,05,02,073,,23,25,329,,21,18,194,*6F
08-08 20:21:38.622 D/GpsOutputNmea( 6280): 1533752498584,$GLGSV,3,3,10,07,61,289,,08,14,262,*6C
08-08 20:21:38.623 W/GpsTestUtil( 6280): Empty DOP values in NMEA: $GPGSA,A,1,,,,,,,,,,,,,,,*1E
08-08 20:21:38.624 D/GpsOutputNmea( 6280): 1533752498585,$GPGSA,A,1,,,,,,,,,,,,,,,*1E
08-08 20:21:38.624 W/GpsTestUtil( 6280): Empty DOP values in NMEA: $GNGSA,A,1,,,,,,,,,,,,,,,*00
08-08 20:21:38.624 D/GpsOutputNmea( 6280): 1533752498585,$GNGSA,A,1,,,,,,,,,,,,,,,*00
08-08 20:21:38.624 D/GpsOutputNmea( 6280): 1533752498585,$GPVTG,,T,,M,,N,,K,N*2C
08-08 20:21:38.624 D/GpsOutputNmea( 6280): 1533752498585,$GPRMC,,V,,,,,,,,,,N*53
08-08 20:21:38.624 W/GpsTestUtil( 6280): Couldn't parse geoid altitude from NMEA: $GPGGA,,,,,,0,,,,,,,,*66
08-08 20:21:38.625 D/GpsOutputNmea( 6280): 1533752498585,$GPGGA,,,,,,0,,,,,,,,*66
08-08 20:21:38.674 E/LocSvc_ApiV02(  827): I/<--- void globalEventCb(locClientHandleType, uint32_t, const locClientEventIndUnionType, void *) line 107 QMI_LOC_EVENT_GNSS_SV_INFO_IND_V02
08-08 20:21:38.675 E/LocSvc_eng(  827): E/Calling gnss_sv_status_cb
08-08 20:21:38.675 E/LocSvc_ApiV02(  827): I/<--- void globalEventCb(locClientHandleType, uint32_t, const locClientEventIndUnionType, void *) line 107 QMI_LOC_EVENT_POSITION_REPORT_IND_V02
08-08 20:21:38.808 I/MSM-irqbalance(  280): Decided to move IRQ270 from CPU2 [P:0] to CPU5 [P:1] (banned)
08-08 20:21:39.017 D/GpsOutputNmea( 6280): 1533752498675,$GPGSV,3,1,12,03,63,088,25,22,40,099,21,01,23,156,,06,38,303,*71
08-08 20:21:39.018 D/GpsOutputNmea( 6280): 1533752498675,$GPGSV,3,2,12,09,43,223,,11,01,167,,17,23,246,,18,00,000,*79
08-08 20:21:39.018 D/GpsOutputNmea( 6280): 1533752498675,$GPGSV,3,3,12,19,29,272,,23,76,192,,25,01,001,,31,18,040,*7C
08-08 20:21:39.018 D/GpsOutputNmea( 6280): 1533752498675,$GLGSV,3,1,10,06,52,052,,22,52,254,,09,03,137,,16,28,088,*66
08-08 20:21:39.019 D/GpsOutputNmea( 6280): 1533752498675,$GLGSV,3,2,10,15,17,021,,05,02,073,,23,25,329,,21,18,194,*6F
08-08 20:21:39.019 D/GpsOutputNmea( 6280): 1533752498676,$GLGSV,3,3,10,07,61,289,,08,14,262,*6C
08-08 20:21:39.020 W/GpsTestUtil( 6280): Empty DOP values in NMEA: $GPGSA,A,1,,,,,,,,,,,,,,,*1E
08-08 20:21:39.020 D/GpsOutputNmea( 6280): 1533752498676,$GPGSA,A,1,,,,,,,,,,,,,,,*1E
08-08 20:21:39.020 W/GpsTestUtil( 6280): Empty DOP values in NMEA: $GNGSA,A,1,,,,,,,,,,,,,,,*00
08-08 20:21:39.020 D/GpsOutputNmea( 6280): 1533752498676,$GNGSA,A,1,,,,,,,,,,,,,,,*00
08-08 20:21:39.021 D/GpsOutputNmea( 6280): 1533752498676,$GPVTG,,T,,M,,N,,K,N*2C
08-08 20:21:39.021 D/GpsOutputNmea( 6280): 1533752498676,$GPRMC,,V,,,,,,,,,,N*53
08-08 20:21:39.021 W/GpsTestUtil( 6280): Couldn't parse geoid altitude from NMEA: $GPGGA,,,,,,0,,,,,,,,*66
08-08 20:21:39.021 D/GpsOutputNmea( 6280): 1533752498676,$GPGGA,,,,,,0,,,,,,,,*66
08-08 20:21:39.675 E/LocSvc_ApiV02(  827): I/<--- void globalEventCb(locClientHandleType, uint32_t, const locClientEventIndUnionType, void *) line 107 QMI_LOC_EVENT_GNSS_SV_INFO_IND_V02
08-08 20:21:39.676 E/LocSvc_eng(  827): E/Calling gnss_sv_status_cb
08-08 20:21:39.677 E/LocSvc_ApiV02(  827): I/<--- void globalEventCb(locClientHandleType, uint32_t, const locClientEventIndUnionType, void *) line 107 QMI_LOC_EVENT_POSITION_REPORT_IND_V02
08-08 20:21:39.678 D/GpsOutputNmea( 6280): 1533752499676,$GPGSV,3,1,12,01,23,156,23,03,63,088,23,22,40,099,21,31,18,040,21*77
08-08 20:21:39.678 D/GpsOutputNmea( 6280): 1533752499676,$GPGSV,3,2,12,06,38,303,,09,43,223,,11,01,167,,17,23,246,*7D
08-08 20:21:39.678 D/GpsOutputNmea( 6280): 1533752499676,$GPGSV,3,3,12,18,00,000,,19,29,272,,23,76,192,,25,01,001,*7A
08-08 20:21:39.679 D/GpsOutputNmea( 6280): 1533752499676,$GLGSV,3,1,10,06,52,052,,22,52,254,,09,03,137,,16,28,088,*66
08-08 20:21:39.913 D/GpsOutputNmea( 6280): 1533752499676,$GLGSV,3,2,10,15,17,021,,05,02,073,,23,25,329,,21,18,194,*6F
08-08 20:21:39.913 D/GpsOutputNmea( 6280): 1533752499676,$GLGSV,3,3,10,07,61,289,,08,14,262,*6C
08-08 20:21:39.913 W/GpsTestUtil( 6280): Empty DOP values in NMEA: $GPGSA,A,1,,,,,,,,,,,,,,,*1E
08-08 20:21:39.913 D/GpsOutputNmea( 6280): 1533752499677,$GPGSA,A,1,,,,,,,,,,,,,,,*1E
08-08 20:21:39.914 W/GpsTestUtil( 6280): Empty DOP values in NMEA: $GNGSA,A,1,,,,,,,,,,,,,,,*00
08-08 20:21:39.914 D/GpsOutputNmea( 6280): 1533752499677,$GNGSA,A,1,,,,,,,,,,,,,,,*00
08-08 20:21:39.914 D/GpsOutputNmea( 6280): 1533752499677,$GPVTG,,T,,M,,N,,K,N*2C
08-08 20:21:39.914 D/GpsOutputNmea( 6280): 1533752499677,$GPRMC,,V,,,,,,,,,,N*53
08-08 20:21:39.914 W/GpsTestUtil( 6280): Couldn't parse geoid altitude from NMEA: $GPGGA,,,,,,0,,,,,,,,*66
08-08 20:21:39.914 D/GpsOutputNmea( 6280): 1533752499677,$GPGGA,,,,,,0,,,,,,,,*66
08-08 20:21:39.979 I/ActivityManager(  827): START u0 {cmp=com.android.gpstest/.HelpActivity} from uid 10374 on display 0
08-08 20:21:39.980 I/wm_task_moved(  827): [93158,1,21]
08-08 20:21:39.981 I/am_create_activity(  827): [0,267733779,93158,com.android.gpstest/.HelpActivity,NULL,NULL,NULL,0]
08-08 20:21:39.982 I/wm_task_moved(  827): [93158,1,21]
08-08 20:21:39.985 I/am_focused_activity(  827): [0,com.android.gpstest/.HelpActivity,startedActivity]
08-08 20:21:39.985 I/am_pause_activity(  827): [0,20199219,com.android.gpstest/.GpsTestActivity]
08-08 20:21:40.002 D/bsthal  (  827): activate, handle: 1598182235, enabled: 0
08-08 20:21:40.003 I/bsthal  (  827): <BST> disable sensor <BOSCH Rotation Vector Sensor>
08-08 20:21:40.005 I/am_on_paused_called( 6280): [0,com.android.gpstest.GpsTestActivity,handlePauseActivity]
08-08 20:21:40.009 I/am_restart_activity(  827): [0,267733779,93158,com.android.gpstest/.HelpActivity]
08-08 20:21:40.014 I/sysui_count(  827): [window_time_0,6]
08-08 20:21:40.041 I/sf_frame_dur(  283): [com.android.gpstest/com.android.gpstest.GpsTestActivity,2,0,0,1,0,0,0]
08-08 20:21:40.081 D/AndroidRuntime( 6280): Shutting down VM
--------- beginning of crash
08-08 20:21:40.083 E/AndroidRuntime( 6280): FATAL EXCEPTION: main
08-08 20:21:40.083 E/AndroidRuntime( 6280): Process: com.android.gpstest, PID: 6280
08-08 20:21:40.084 I/am_crash(  827): [6280,0,com.android.gpstest,948485700,java.lang.IndexOutOfBoundsException,setSpan (2220 ... 2224) ends beyond length 2198,SpannableStringInternal.java,428]
08-08 20:21:40.083 E/AndroidRuntime( 6280): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.gpstest/com.android.gpstest.HelpActivity}: java.lang.IndexOutOfBoundsException: setSpan (2220 ... 2224) ends beyond length 2198
08-08 20:21:40.083 E/AndroidRuntime( 6280): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
08-08 20:21:40.083 E/AndroidRuntime( 6280): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
08-08 20:21:40.083 E/AndroidRuntime( 6280): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
08-08 20:21:40.083 E/AndroidRuntime( 6280): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
08-08 20:21:40.083 E/AndroidRuntime( 6280): 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-08 20:21:40.083 E/AndroidRuntime( 6280): 	at android.os.Looper.loop(Looper.java:154)
08-08 20:21:40.083 E/AndroidRuntime( 6280): 	at android.app.ActivityThread.main(ActivityThread.java:6186)
08-08 20:21:40.083 E/AndroidRuntime( 6280): 	at java.lang.reflect.Method.invoke(Native Method)
08-08 20:21:40.083 E/AndroidRuntime( 6280): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
08-08 20:21:40.083 E/AndroidRuntime( 6280): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
08-08 20:21:40.083 E/AndroidRuntime( 6280): Caused by: java.lang.IndexOutOfBoundsException: setSpan (2220 ... 2224) ends beyond length 2198
08-08 20:21:40.083 E/AndroidRuntime( 6280): 	at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:428)
08-08 20:21:40.083 E/AndroidRuntime( 6280): 	at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:155)
08-08 20:21:40.083 E/AndroidRuntime( 6280): 	at android.text.SpannableString.setSpan(SpannableString.java:46)
08-08 20:21:40.083 E/AndroidRuntime( 6280): 	at android.content.res.StringBlock.applyStyles(StringBlock.java:179)
08-08 20:21:40.083 E/AndroidRuntime( 6280): 	at android.content.res.StringBlock.get(StringBlock.java:134)
08-08 20:21:40.083 E/AndroidRuntime( 6280): 	at android.content.res.AssetManager.getResourceValue(AssetManager.java:222)
08-08 20:21:40.083 E/AndroidRuntime( 6280): 	at android.content.res.AssetManager.getResourceText(AssetManager.java:161)
08-08 20:21:40.083 E/AndroidRuntime( 6280): 	at android.content.res.Resources.getText(Resources.java:331)
08-08 20:21:40.083 E/AndroidRuntime( 6280): 	at android.widget.TextView.setText(TextView.java:4555)
08-08 20:21:40.083 E/AndroidRuntime( 6280): 	at com.android.gpstest.HelpActivity.onCreate(HelpActivity.java:67)
08-08 20:21:40.083 E/AndroidRuntime( 6280): 	at android.app.Activity.performCreate(Activity.java:6684)
08-08 20:21:40.083 E/AndroidRuntime( 6280): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
08-08 20:21:40.083 E/AndroidRuntime( 6280): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
08-08 20:21:40.083 E/AndroidRuntime( 6280): 	... 9 more
08-08 20:21:40.088 I/am_finish_activity(  827): [0,267733779,93158,com.android.gpstest/.HelpActivity,force-crash]
08-08 20:21:40.088 W/ActivityManager(  827):   Force finishing activity com.android.gpstest/.HelpActivity
08-08 20:21:40.090 I/wm_task_moved(  827): [93158,1,21]
08-08 20:21:40.095 W/ActivityManager(  827):   Force finishing activity com.android.gpstest/.GpsTestActivity
08-08 20:21:40.093 I/am_focused_activity(  827): [0,com.android.gpstest/.GpsTestActivity,finishActivity adjustFocus]
08-08 20:21:40.094 I/am_pause_activity(  827): [0,267733779,com.android.gpstest/.HelpActivity]
08-08 20:21:40.095 I/am_finish_activity(  827): [0,20199219,93158,com.android.gpstest/.GpsTestActivity,force-crash]
08-08 20:21:40.096 I/am_focused_stack(  827): [0,0,1,finishActivity adjustFocus setFocusedActivity]
08-08 20:21:40.097 I/wm_task_moved(  827): [91731,1,1]
08-08 20:21:40.100 I/am_focused_activity(  827): [0,com.cyanogenmod.trebuchet/com.android.launcher3.Launcher,finishActivity adjustFocus]
08-08 20:21:40.164 I/OpenGLRenderer(  827): Initialized EGL, version 1.4
08-08 20:21:40.165 D/OpenGLRenderer(  827): Swap behavior 1
08-08 20:21:40.596 W/ActivityManager(  827): Activity pause timeout for ActivityRecord{ff54b13 u0 com.android.gpstest/.HelpActivity t93158 f}
08-08 20:21:40.601 I/am_resume_activity(  827): [0,43439872,91731,com.cyanogenmod.trebuchet/com.android.launcher3.Launcher]
`

**Comment by barbeau** [comment]
Looks like there is an error in the translated German help string that's causing it to crash. Could you check the URL to be sure it's encoded properly and matches English version? I'll try to look more closely later this week.

**Comment by SIRSteiner** [comment]
Hm... I only changed one word and have remove most " - " at the beginning of discription because that looks better. URLs are the same but before there was "...\n - https ..." and now "...\nhttps..."
Is it a problem?

**Comment by barbeau** [comment]
@SIRSteiner After some testing on an emulator I set to the German language, bizarrely, the crash appears to be caused by a lack of a space in between the newline and URL - so this causes a crash:
`(FAQ)</b>\nhttps`

...but this works fine:
`(FAQ)</b>\n https`

I've made the change to this pull request so it no longer crashes when viewing the "Help->About"  screen on German devices.

Could you please try this APK and see if everything looks good, or if you want to make more changes?

https://www.dropbox.com/s/wamu9dbxvc8xx34/GPSTest-google-release-german-v2.apk?dl=0

**Comment by SIRSteiner** [comment]
That's interesting and I ask myself how to add an new line followed by an url without  space. But I think this isn't a great problem,  most users will not realize this space.
At all: every looks fine! Thank you

**Comment by SIRSteiner** [comment]
Thumbs up!
Additional I have an idea: should we use in html <br> and also special chars in html syntax instead in unicode in the future?

**Comment by barbeau** [comment]
I agree that HTML is a better solution although IIRC there needs to be code changes for that, and other languages would also need to be updated to the new format. So a good plan, but requires some work.

**Pull request merged**
